
- name: Install or uninstall software packages
  package:
    name: "{{ item }}"
    state: "{{ software_package_state | default('present') }}"
  with_items: "{{ software_packages }}"
  tags: 
    - install
    - uninstall
    - never

- name: Manage service state
  systemd:
    name: "{{ item }}"
    state: "{{ software_service_state }}"
  with_items: "{{ software_services }}"
  when: software_services is defined
  tags: 
    - started
    - stopped
    - restarted
