 - name: Install Nginx on Debian (e.g., Ubuntu)
      package:
        name:
        state: present
      when: ansible_os_family == 'Debian'
      tags:
        - install_software
    
    - name: Install Nginx on RedHat
      package:
        name: 
        state: present
      when: ansible_os_family == 'RedHat'
      tags:
        - install_software
        
    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp
